name: central-midias-api

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - central_midias_api_redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: backoffice-prd
    image: central-midias-api
    expose:
      - '4000'
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --quiet --tries=1 --spider http://localhost:4000/api/health || curl -f http://localhost:4000/api/health || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - default
      - proxy

volumes:
  central_midias_api_redis_data:
    name: central-midias-api-redis-data

networks:
  default:
    driver: bridge
  proxy:
    external: true
