export const userRoles = {
  ADMIN: 'ADMIN',
  COLLABORATOR: 'COLLABORATOR',
  OWN_DIRECT_CHANNEL: 'OWN_DIRECT_CHANNEL',
  AGENT_DIRECT_CHANNEL: 'AGENT_DIRECT_CHANNEL',
  SMALL_MASTER_AGENT: 'SMALL_MASTER_AGENT',
  MEDIUM_MASTER_AGENT: 'MEDIUM_MASTER_AGENT',
  LARGE_MASTER_AGENT: 'LARGE_MASTER_AGENT',
  PARTNER: 'PARTNER',
  AGENT_EMPLOYEE: 'AGENT_EMPLOYEE',
};

export type UserRole = (typeof userRoles)[keyof typeof userRoles];
