export const MAX_IMAGE_PLACEHOLDERS = 20;
export const PRINT_IMAGE_MAX_BYTES = 5 * 1024 * 1024;
export const PRINT_IMAGE_MAX_SIDE = 6000;
export const PRINT_IMAGE_MAX_PIXELS = 30_000_000;
export const PRINT_INPUT_TTL_MS = 24 * 60 * 60 * 1000;
export const PRINT_MULTIPART_FIELD_BYTES = 3 * 1024 * 1024;
export const PRINT_MULTIPART_MAX_BYTES =
  MAX_IMAGE_PLACEHOLDERS * PRINT_IMAGE_MAX_BYTES +
  3 * PRINT_MULTIPART_FIELD_BYTES;
